### ISSUE TITLE
How to generate the testing data?

### ISSUE THREAD

**Issue by cuge1995** [HanjiangHu/Multi-LiDAR-Placement-for-3D-Detection#2]

**Comment by HanjiangHu** [comment]
The collected data is called "training" and then we need to split them to get testing or validation data. To split the training and test set for the experiment, copy  `./OpenPCDet/tools/split_training_test.py` to the root path of the collected dataset (e.g. `./carla-kitti/dataset/center/`) and run `split_training_test.py``  under that path. Maybe in the future we will release the code to collect test data directly from CARLA, which is out of the scope of our paper.
