### ISSUE TITLE
pom.py question

### ISSUE THREAD

**Issue by lijin123red** [HanjiangHu/Multi-LiDAR-Placement-for-3D-Detection#4]
Hello, thanks for your work! I have a question about code in pom.py, In your paper, you introduce that a voxel is occupied if it is within any of the bounding boxes in one frame,   so if in one frame with 9 bboxes,the 9 bboxes occupy one voxel with coordinate(x,y,z) jointly,  then the variable "occupancy(x,y,z)" should equal to 1  rather than 9. Is my understanding correct? Looking forward to your reply.

**Comment by HanjiangHu** [comment]
Thanks for your interest in our work. The occupancy of voxels is regarding the time sequence. So "occupancy(x,y,z)" should be calculated as the number of frames that (x,y,z) is occupied divided by the number of total frames. In the one-frame case, the occupancy is actually binary (0 or 1). Hope you find the clarification helpful.
